// Catalogo de capacidades por categoria de segmento.
// status: "available" = ja funciona no sistema | "soon" = no roadmap (em construcao).
import type { SegmentCategory } from "@/segments/types";

export type CapStatus = "available" | "soon";

export interface CapItem {
  label: string;
  status: CapStatus;
}

export interface CapGroup {
  id: string;
  title: string;
  icon: string;
  items: CapItem[];
}

export interface IntegrationRef {
  label: string;
  icon: string;
}

export interface SegmentExtras {
  intro: string;
  groups: CapGroup[];
  premium: CapGroup[];
  dashboards: string[];
  integrations: IntegrationRef[];
  differentials: string[];
}

const a = (label: string): CapItem => ({ label, status: "available" });
const s = (label: string): CapItem => ({ label, status: "soon" });

const BELEZA: SegmentExtras = {
  intro:
    "Um conjunto premium de funcionalidades para profissionais e negócios de beleza e estética — do autônomo às redes e franquias.",
  groups: [
    {
      id: "agenda",
      title: "Agenda inteligente",
      icon: "Calendar",
      items: [
        a("Agenda por profissional"),
        a("Bloqueio de horários"),
        a("Reagendamento fácil"),
        a("Agendamento online (link do cliente)"),
        s("Agenda por sala / cabine"),
        s("Confirmação automática"),
        s("Lista de espera"),
        s("Recorrência de horários"),
      ],
    },
    {
      id: "crm",
      title: "Clientes (CRM)",
      icon: "Users",
      items: [
        a("Histórico completo de atendimentos"),
        a("Preferências e observações"),
        a("Anamnese e alergias"),
        a("Campos próprios do segmento"),
        s("Fotos antes/depois"),
        s("Documentos e consentimentos digitais"),
      ],
    },
    {
      id: "servicos",
      title: "Serviços",
      icon: "Tag",
      items: [
        a("Cadastro ilimitado"),
        a("Tempo de execução e valor"),
        a("Profissional habilitado"),
        a("Comissão por serviço"),
        a("Pacotes, combos e assinaturas"),
        s("Materiais utilizados por serviço"),
      ],
    },
    {
      id: "financeiro",
      title: "Financeiro",
      icon: "Wallet",
      items: [
        a("Caixa diário"),
        a("Contas a pagar e a receber"),
        a("Fluxo de caixa"),
        a("Controle de inadimplência"),
        s("PIX e cartão integrados"),
        s("Parcelamento e carnê"),
        s("Cashback e vale-presente"),
      ],
    },
    {
      id: "comissao",
      title: "Comissão",
      icon: "Percent",
      items: [
        a("Comissão por serviço"),
        a("Comissão por produto"),
        s("Comissão variável e metas"),
        s("Ranking de profissionais"),
        s("Fechamento automático"),
      ],
    },
    {
      id: "estoque",
      title: "Estoque",
      icon: "Boxes",
      items: [
        a("Entrada e saída"),
        a("Inventário e estoque mínimo"),
        a("Baixa por atendimento"),
        s("Validade e lote"),
        s("Compras e fornecedores"),
      ],
    },
    {
      id: "vendas",
      title: "Vendas e PDV",
      icon: "ShoppingCart",
      items: [
        a("Venda de produtos e kits"),
        a("Combos e pacotes"),
        s("Vale-presente"),
        s("Assinaturas"),
        a("PDV completo"),
      ],
    },
    {
      id: "marketing",
      title: "Marketing e fidelização",
      icon: "Megaphone",
      items: [
        s("WhatsApp, SMS e e-mail"),
        s("Campanhas automáticas"),
        s("Aniversariantes e clientes inativos"),
        s("Cupons e programa de fidelidade"),
        s("Indicação de clientes"),
      ],
    },
    {
      id: "profissionais",
      title: "Profissionais",
      icon: "UserCog",
      items: [
        a("Agenda individual"),
        a("Papéis e permissões"),
        s("Escala, jornada e folgas"),
        s("Metas individuais"),
        s("Produtividade"),
      ],
    },
    {
      id: "unidades",
      title: "Múltiplas unidades",
      icon: "Building2",
      items: [
        s("Franquias e filiais"),
        s("Controle centralizado"),
        s("Comparativo entre unidades"),
        s("Transferência de estoque"),
      ],
    },
  ],
  premium: [
    {
      id: "ia",
      title: "Inteligência artificial",
      icon: "Bot",
      items: [
        a("Sugestão automática de horários"),
        s("Previsão de faltas (no-show)"),
        s("Sugestão de serviços e produtos"),
        s("Chatbot e atendimento automático"),
      ],
    },
    {
      id: "app-cliente",
      title: "Aplicativo do cliente",
      icon: "Smartphone",
      items: [
        a("Agendar, cancelar e reagendar"),
        s("Histórico e carteira"),
        s("Cashback e pontos"),
        s("Avaliação e chat"),
      ],
    },
    {
      id: "area-prof",
      title: "Área do profissional",
      icon: "GanttChartSquare",
      items: [
        s("Agenda e clientes"),
        s("Comissão e metas"),
        s("Fotos e relatórios"),
      ],
    },
    {
      id: "fotos",
      title: "Fotos e evolução",
      icon: "Camera",
      items: [
        s("Antes e depois"),
        s("Comparação e álbuns"),
        s("Linha do tempo de evolução"),
      ],
    },
    {
      id: "assinaturas",
      title: "Assinaturas",
      icon: "Repeat",
      items: [
        s("Plano mensal e anual"),
        s("Renovação automática"),
        s("Cobrança recorrente"),
      ],
    },
    {
      id: "documentos",
      title: "Documentos",
      icon: "FileSignature",
      items: [
        s("Assinatura digital"),
        s("Termos de consentimento (LGPD)"),
        s("Contratos"),
      ],
    },
  ],
  dashboards: [
    "Faturamento diário e mensal",
    "Ticket médio",
    "Clientes novos e recorrentes",
    "Taxa de retorno e no-show",
    "Ocupação da agenda",
    "Serviços e produtos mais vendidos",
    "Profissionais mais produtivos",
    "Comissão, lucro e margem",
    "Alertas de estoque baixo no painel",
    "Clientes inativos",
    "NPS (satisfação)",
  ],
  integrations: [
    { label: "WhatsApp", icon: "MessageCircle" },
    { label: "Instagram", icon: "Sparkles" },
    { label: "Google Agenda", icon: "Calendar" },
    { label: "Google Maps", icon: "Globe" },
    { label: "PIX", icon: "Wallet" },
    { label: "Cartão e maquininhas", icon: "CreditCard" },
    { label: "NF-e / NFS-e", icon: "FileText" },
    { label: "Contabilidade / ERP", icon: "Layers" },
  ],
  differentials: [
    "Agenda com IA que otimiza os horários automaticamente",
    "Confirmação por WhatsApp com respostas inteligentes",
    "Reconhecimento facial do cliente no check-in",
    "Análise de rentabilidade por profissional, serviço e cabine",
    "Previsão de faturamento dos próximos dias",
    "Business Intelligence (BI) em tempo real",
    "Programa de fidelidade e CRM com marketing automático",
    "Estoque vinculado ao consumo por procedimento",
    "Prontuário estético digital com fotos e documentos assinados",
    "Gestão de franquias e múltiplas unidades",
    "Aplicativo próprio para clientes e profissionais",
  ],
};

const ALIMENTACAO: SegmentExtras = {
  intro:
    "Uma operação completa do pedido ao financeiro — do pequeno estabelecimento às grandes redes de alimentação.",
  groups: [
    {
      id: "pdv",
      title: "PDV (frente de caixa)",
      icon: "CreditCard",
      items: [
        a("Comanda / pedido eletrônico"),
        a("Venda por mesa e balcão"),
        s("Venda rápida (PDV dedicado)"),
        s("Divisão de conta e pagamento parcial"),
        s("PIX, cartão e dinheiro integrados"),
        s("Cashback e vale-presente"),
      ],
    },
    {
      id: "mesas",
      title: "Gestão de mesas",
      icon: "UtensilsCrossed",
      items: [
        a("Mapa do salão e status das mesas"),
        a("Abrir venda no PDV pela mesa"),
        s("Reserva e lista de espera"),
        s("Transferência e junção de mesas"),
        s("Tempo de permanência"),
      ],
    },
    {
      id: "cardapio",
      title: "Cardápio digital",
      icon: "QrCode",
      items: [
        a("Categorias e produtos"),
        a("Preços sempre atualizados"),
        s("QR Code com fotos"),
        s("Adicionais, combos e promoções"),
        s("Disponibilidade em tempo real"),
      ],
    },
    {
      id: "pedidos",
      title: "Pedidos",
      icon: "Receipt",
      items: [
        a("Balcão e mesa"),
        s("Delivery e retirada"),
        s("Garçom via celular / tablet"),
        s("Autoatendimento (totem)"),
        s("Aplicativo próprio"),
      ],
    },
    {
      id: "kds",
      title: "Cozinha (KDS)",
      icon: "ChefHat",
      items: [
        a("Painel de produção e fila de pedidos"),
        a("Status do pedido (pendente, preparando, pronto)"),
        s("Tempo de preparo e prioridade"),
        s("Impressão por setor (cozinha, bar, pizzaria)"),
      ],
    },
    {
      id: "delivery",
      title: "Delivery",
      icon: "Bike",
      items: [
        s("Entregadores e controle de rotas"),
        s("Rastreamento em tempo real"),
        s("Taxa de entrega e tempo estimado"),
        s("Histórico e avaliação"),
      ],
    },
    {
      id: "estoque",
      title: "Estoque e ficha técnica",
      icon: "Boxes",
      items: [
        a("Entrada e saída"),
        a("Inventário e estoque mínimo"),
        s("Ficha técnica com custo e rendimento"),
        s("Baixa automática por venda"),
        s("Perdas, validade e produção"),
        s("Compras e fornecedores"),
      ],
    },
    {
      id: "financeiro",
      title: "Financeiro",
      icon: "Wallet",
      items: [
        a("Fluxo de caixa"),
        a("Contas a pagar e a receber"),
        a("Fechamento diário"),
        s("DRE e centros de custo"),
        s("Conciliação bancária"),
        s("CMV (custo da mercadoria vendida)"),
      ],
    },
    {
      id: "crm",
      title: "Clientes (CRM)",
      icon: "Users",
      items: [
        a("Histórico e pedidos anteriores"),
        a("Preferências e observações"),
        s("Fidelidade, cashback e pontuação"),
        s("Cupons e aniversariantes"),
      ],
    },
    {
      id: "funcionarios",
      title: "Funcionários",
      icon: "UserCog",
      items: [
        a("Garçom, cozinha, caixa e gerência"),
        a("Papéis e permissões"),
        s("Escalas e metas"),
        s("Comissão, gorjetas e produtividade"),
      ],
    },
  ],
  premium: [
    {
      id: "autoatendimento",
      title: "Autoatendimento",
      icon: "QrCode",
      items: [s("Totem"), s("Tablet na mesa"), s("QR Code"), s("Pedido pelo celular")],
    },
    {
      id: "ia",
      title: "Inteligência artificial",
      icon: "Bot",
      items: [
        s("Previsão de demanda e de faturamento"),
        s("Sugestão de compras e de promoções"),
        s("Previsão de estoque"),
        s("Análise de desperdício"),
      ],
    },
    {
      id: "marketing",
      title: "Marketing",
      icon: "Megaphone",
      items: [
        s("WhatsApp, SMS e e-mail"),
        s("Cupons automáticos"),
        s("Clientes inativos"),
        s("Promoções por horário e fidelidade"),
      ],
    },
    {
      id: "unidades",
      title: "Múltiplas unidades",
      icon: "Building2",
      items: [
        s("Franquias e comparativo"),
        s("Estoque central e transferências"),
        s("Gestão centralizada"),
      ],
    },
    {
      id: "app-cliente",
      title: "Aplicativo do cliente",
      icon: "Smartphone",
      items: [
        s("Cardápio, pedido e pagamento"),
        s("Rastreamento do pedido"),
        s("Cashback, fidelidade e histórico"),
        s("Avaliações"),
      ],
    },
    {
      id: "delivery-proprio",
      title: "Delivery próprio",
      icon: "Bike",
      items: [
        s("Aplicativo do entregador"),
        s("Rastreamento em tempo real"),
        s("Controle de rotas e entregas"),
      ],
    },
  ],
  dashboards: [
    "Faturamento diário e ticket médio",
    "Lucro, margem e CMV",
    "Pedidos por hora",
    "Tempo médio de preparo e de entrega",
    "Produtos mais vendidos",
    "Ingredientes mais consumidos",
    "Desperdício",
    "Clientes recorrentes",
    "Ocupação das mesas",
    "Vendas por garçom e por unidade",
    "Ranking de produtos",
    "Fluxo de caixa",
  ],
  integrations: [
    { label: "PIX", icon: "Wallet" },
    { label: "Cartões", icon: "CreditCard" },
    { label: "NFC-e / NFS-e", icon: "FileText" },
    { label: "Impressoras térmicas", icon: "Receipt" },
    { label: "Balanças", icon: "Scale" },
    { label: "WhatsApp", icon: "MessageCircle" },
    { label: "Google Maps", icon: "MapPin" },
    { label: "iFood, Uber Eats e Rappi", icon: "Bike" },
    { label: "Contabilidade / ERP", icon: "Layers" },
  ],
  differentials: [
    "Cardápio digital inteligente com QR Code",
    "Painel de cozinha (KDS) totalmente integrado",
    "Autoatendimento por QR Code, tablet e totem",
    "Delivery próprio com rastreamento em tempo real",
    "Controle automático de estoque pelas fichas técnicas",
    "IA para previsão de demanda, compras e desperdício",
    "Gestão completa de mesas e reservas",
    "CRM com fidelidade, cashback e campanhas automáticas",
    "Business Intelligence (BI) em tempo real",
    "Gestão de franquias e múltiplas unidades",
    "Apps próprios para clientes, garçons e entregadores",
    "Controle de custos e CMV para maximizar a lucratividade",
  ],
};

const SAUDE: SegmentExtras = {
  intro:
    "Uma plataforma completa para a saúde — da agenda ao prontuário, do financeiro ao relacionamento com o paciente. Do profissional autônomo às clínicas e redes.",
  groups: [
    {
      id: "agenda",
      title: "Agenda inteligente",
      icon: "Calendar",
      items: [
        a("Agenda por profissional"),
        a("Reagendamento e bloqueio de horários"),
        a("Atendimento recorrente"),
        a("Agendamento online (link do paciente)"),
        s("Confirmação automática"),
        s("Lista de espera"),
        s("Teleconsulta"),
      ],
    },
    {
      id: "pacientes",
      title: "Cadastro de pacientes / alunos",
      icon: "Users",
      items: [
        a("Histórico completo e contatos"),
        a("Convênios e responsáveis"),
        a("Anamnese, alergias e observações"),
        s("Documentos e fotos anexados"),
        s("Assinatura digital"),
      ],
    },
    {
      id: "prontuario",
      title: "Prontuário eletrônico",
      icon: "ClipboardList",
      items: [
        a("Evolução e histórico completo"),
        a("Anexos e fotos"),
        s("Prescrições e receitas"),
        s("Solicitação de exames e laudos"),
        s("Atestados"),
      ],
    },
    {
      id: "financeiro",
      title: "Financeiro",
      icon: "Wallet",
      items: [
        a("Caixa e fluxo de caixa"),
        a("Contas a pagar e a receber"),
        a("Convênios e particulares"),
        s("PIX e cartão integrados"),
        s("Cobrança recorrente"),
        s("Controle de inadimplência"),
      ],
    },
    {
      id: "planos",
      title: "Planos e assinaturas",
      icon: "Repeat",
      items: [
        a("Pacotes de sessões"),
        a("Controle de vencimentos"),
        s("Planos mensais e mensalidades"),
        s("Renovação automática"),
        s("Cobrança recorrente"),
      ],
    },
    {
      id: "profissionais",
      title: "Gestão dos profissionais",
      icon: "UserCog",
      items: [
        a("Agenda por profissional"),
        a("Atendimentos realizados"),
        s("Escalas"),
        s("Comissão e metas"),
        s("Produtividade"),
      ],
    },
    {
      id: "documentos",
      title: "Documentos",
      icon: "FileSignature",
      items: [
        s("Receitas, atestados e declarações"),
        s("Contratos e consentimentos"),
        s("Termos de LGPD"),
        s("Assinatura eletrônica"),
      ],
    },
    {
      id: "estoque",
      title: "Estoque",
      icon: "Boxes",
      items: [
        a("Materiais e produtos"),
        a("Inventário e fornecedores"),
        s("Medicamentos com lote e validade"),
      ],
    },
    {
      id: "especialidade",
      title: "Recursos por especialidade",
      icon: "Stethoscope",
      items: [
        s("Médico: CID, prescrição digital, exames e telemedicina"),
        s("Odontologia: odontograma, plano de tratamento e evolução por dente"),
        s("Psicologia: evolução terapêutica e anotações sigilosas"),
        s("Fisioterapia: plano terapêutico, exercícios e escalas de avaliação"),
        s("Nutrição: avaliação antropométrica, plano e diário alimentar"),
        s("Academia: matrículas, treinos, avaliação física e frequência"),
      ],
    },
  ],
  premium: [
    {
      id: "app-paciente",
      title: "Aplicativo do paciente / aluno",
      icon: "Smartphone",
      items: [
        s("Agendamento e cancelamento"),
        s("Teleconsulta e chat"),
        s("Resultados, receitas e histórico"),
        s("Pagamentos"),
        s("Treinos e plano alimentar"),
      ],
    },
    {
      id: "ia",
      title: "Inteligência artificial",
      icon: "Bot",
      items: [
        s("Lembretes automáticos"),
        s("Previsão de faltas e sugestão de retorno"),
        s("Evolução em gráfico"),
        s("Resumo inteligente do prontuário"),
        s("Chat de atendimento"),
      ],
    },
    {
      id: "crm",
      title: "Marketing (CRM)",
      icon: "Megaphone",
      items: [
        s("WhatsApp, SMS e e-mail"),
        s("Campanhas e aniversariantes"),
        s("Pacientes inativos"),
        s("Pesquisa de satisfação"),
      ],
    },
    {
      id: "unidades",
      title: "Múltiplas unidades",
      icon: "Building2",
      items: [
        s("Gestão centralizada e comparativo"),
        s("Transferência de pacientes"),
        s("Gestão de franquias"),
      ],
    },
    {
      id: "teleconsulta",
      title: "Teleconsulta",
      icon: "Video",
      items: [
        s("Atendimento por vídeo integrado à agenda"),
        s("Sala de espera virtual"),
        s("Receitas e documentos pós-consulta"),
      ],
    },
    {
      id: "acesso",
      title: "Controle de acesso (academias)",
      icon: "Fingerprint",
      items: [
        s("Biometria e catracas"),
        s("Frequência dos alunos"),
        s("Bloqueio por inadimplência"),
      ],
    },
  ],
  dashboards: [
    "Consultas e sessões realizadas",
    "Pacientes ativos e novos pacientes",
    "Taxa de retorno",
    "No-show (faltas)",
    "Agenda ocupada e ocupação por horário",
    "Faturamento e evolução financeira",
    "Inadimplência",
    "Ticket médio",
    "Convênios",
    "Profissionais mais produtivos",
    "Alunos ativos (academias)",
    "Frequência dos alunos",
  ],
  integrations: [
    { label: "WhatsApp", icon: "MessageCircle" },
    { label: "PIX", icon: "Wallet" },
    { label: "Cartões", icon: "CreditCard" },
    { label: "NFS-e", icon: "FileText" },
    { label: "Convênios", icon: "ShieldCheck" },
    { label: "Laboratórios", icon: "Pill" },
    { label: "Teleconsulta", icon: "Video" },
    { label: "Google Agenda", icon: "Calendar" },
    { label: "Google Meet", icon: "Video" },
    { label: "Biometria e catracas", icon: "Fingerprint" },
    { label: "Contabilidade / ERP", icon: "Layers" },
  ],
  differentials: [
    "Prontuário eletrônico personalizável por especialidade",
    "Agendamento online com confirmação automática",
    "Teleconsulta integrada",
    "Aplicativo completo para pacientes e alunos",
    "IA para resumir prontuários e sugerir retornos",
    "Gestão completa de planos, mensalidades e pacotes",
    "CRM com automação de relacionamento",
    "Business Intelligence (BI) em tempo real",
    "Controle de acesso para academias (biometria e catracas)",
    "Gestão de múltiplas unidades e franquias",
    "Assinatura eletrônica de documentos e consentimentos",
    "Painéis com indicadores clínicos e financeiros",
  ],
};

const SERVICOS: SegmentExtras = {
  intro:
    "Tudo para profissionais e escritórios de serviços — do primeiro contato à cobrança. CRM, demandas, documentos e financeiro integrados, do autônomo às redes.",
  groups: [
    {
      id: "crm",
      title: "CRM de clientes",
      icon: "Users",
      items: [
        a("Cadastro completo e histórico de atendimentos"),
        a("Observações e anexos"),
        s("Documentos e contratos por cliente"),
        s("Funil de atendimento"),
      ],
    },
    {
      id: "agenda",
      title: "Agenda inteligente",
      icon: "Calendar",
      items: [
        a("Compromissos, reuniões e visitas"),
        a("Controle de prazos"),
        a("Agenda por profissional"),
        s("Lembretes automáticos"),
        s("Agenda compartilhada"),
      ],
    },
    {
      id: "servicos",
      title: "Gestão de serviços",
      icon: "ClipboardList",
      items: [
        a("Ordens de serviço e solicitações"),
        a("Andamento, status e responsáveis"),
        a("Histórico completo"),
        s("Protocolos e prioridades"),
      ],
    },
    {
      id: "documentos",
      title: "Documentos",
      icon: "FolderOpen",
      items: [
        s("Contratos, procurações e propostas"),
        s("Orçamentos e modelos personalizados"),
        s("Armazenamento digital"),
        s("Assinatura eletrônica"),
      ],
    },
    {
      id: "financeiro",
      title: "Financeiro",
      icon: "Wallet",
      items: [
        a("Caixa e fluxo de caixa"),
        a("Contas a pagar e a receber"),
        a("Honorários"),
        s("Mensalidades e cobrança recorrente"),
        s("PIX e cartão integrados"),
        s("Controle de inadimplência"),
      ],
    },
    {
      id: "equipe",
      title: "Equipe",
      icon: "UserCog",
      items: [
        a("Usuários e perfis de acesso"),
        a("Agenda individual"),
        s("Metas e produtividade"),
        s("Comissões"),
        s("Controle de tarefas"),
      ],
    },
    {
      id: "tarefas",
      title: "Gestão de tarefas",
      icon: "KanbanSquare",
      items: [
        s("Kanban e checklist"),
        s("Subtarefas e prazos"),
        s("Alertas e comentários"),
        s("Anexos"),
      ],
    },
    {
      id: "area",
      title: "Recursos por área",
      icon: "Briefcase",
      items: [
        s("Advocacia: processos, prazos, audiências e andamentos"),
        s("Contabilidade: empresas, obrigações fiscais e guias"),
        s("Imobiliária: imóveis, captação, propostas e contratos"),
        s("Assistência técnica: OS, diagnóstico, peças e garantia"),
        s("Consultorias: projetos, cronogramas, entregas e horas"),
      ],
    },
  ],
  premium: [
    {
      id: "portal",
      title: "Portal do cliente",
      icon: "Globe",
      items: [
        a("Acompanhamento dos serviços em tempo real"),
        a("Histórico"),
        s("Documentos, contratos e boletos"),
        s("Mensagens e solicitações"),
      ],
    },
    {
      id: "ia",
      title: "Inteligência artificial",
      icon: "Bot",
      items: [
        s("Resumo automático de documentos"),
        s("Geração de contratos"),
        s("Organização de tarefas e sugestão de prioridades"),
        s("Chat inteligente e automação de respostas"),
      ],
    },
    {
      id: "marketing",
      title: "Marketing (CRM)",
      icon: "Megaphone",
      items: [
        s("WhatsApp, e-mail e SMS"),
        s("Automação de propostas e follow-up"),
        s("Campanhas"),
        s("Pesquisa de satisfação"),
      ],
    },
    {
      id: "unidades",
      title: "Múltiplas unidades",
      icon: "Building2",
      items: [
        s("Gestão centralizada e comparativo"),
        s("Filiais"),
        s("Franquias"),
      ],
    },
    {
      id: "app",
      title: "Aplicativo para equipe e clientes",
      icon: "Smartphone",
      items: [
        s("Acesso remoto às informações"),
        s("Acompanhamento dos serviços"),
        s("Tarefas e agenda na palma da mão"),
      ],
    },
  ],
  dashboards: [
    "Clientes ativos e novos clientes",
    "Serviços em andamento e concluídos",
    "Prazos próximos",
    "Produtividade da equipe",
    "Faturamento e fluxo de caixa",
    "Inadimplência",
    "Ticket médio",
    "Conversão de propostas",
    "Tempo médio de atendimento",
    "Rentabilidade por cliente",
    "Rentabilidade por serviço",
  ],
  integrations: [
    { label: "WhatsApp", icon: "MessageCircle" },
    { label: "E-mail", icon: "Mail" },
    { label: "Google Agenda", icon: "Calendar" },
    { label: "Google Drive", icon: "FolderOpen" },
    { label: "OneDrive", icon: "FolderOpen" },
    { label: "Dropbox", icon: "FolderOpen" },
    { label: "PIX", icon: "Wallet" },
    { label: "Cartões", icon: "CreditCard" },
    { label: "NFS-e", icon: "FileText" },
    { label: "Assinatura eletrônica", icon: "FileSignature" },
    { label: "Contabilidade / ERP", icon: "Layers" },
  ],
  differentials: [
    "CRM completo com funil comercial e histórico do cliente",
    "Gestão documental com assinatura eletrônica integrada",
    "Portal do cliente para acompanhamento em tempo real",
    "Kanban e gestão de tarefas totalmente integrados",
    "IA para gerar contratos, resumir documentos e organizar demandas",
    "Automação de cobranças, lembretes e follow-ups",
    "Business Intelligence (BI) em tempo real",
    "Gestão financeira integrada aos serviços",
    "Controle de múltiplas unidades e franquias",
    "Aplicativo para equipe e clientes com acesso remoto",
  ],
};

const AUTOMOTIVO: SegmentExtras = {
  intro:
    "Tudo para o seu negócio automotivo — da entrada do veículo à entrega. Ordem de serviço digital, peças, orçamentos e financeiro integrados, da oficina às redes e franquias.",
  groups: [
    {
      id: "agenda",
      title: "Agenda inteligente",
      icon: "Calendar",
      items: [
        a("Agendamento de serviços"),
        a("Agenda por mecânico"),
        a("Reagendamento"),
        s("Agenda por box / elevador"),
        s("Confirmação automática"),
        s("Controle de capacidade diária"),
      ],
    },
    {
      id: "veiculos",
      title: "Clientes e veículos",
      icon: "Car",
      items: [
        a("Dados do proprietário"),
        a("Placa, modelo, ano e quilometragem"),
        a("Histórico completo do veículo"),
        s("Chassi (VIN) e documentos"),
        s("Fotos e histórico de revisões"),
      ],
    },
    {
      id: "os",
      title: "Ordem de serviço (OS)",
      icon: "ClipboardList",
      items: [
        a("Abertura da OS e serviços executados"),
        a("Peças utilizadas"),
        a("Status em tempo real"),
        s("Checklist de entrada e diagnóstico"),
        s("Fotos antes e depois"),
        s("Aprovação digital e garantia"),
      ],
    },
    {
      id: "orcamentos",
      title: "Orçamentos",
      icon: "Receipt",
      items: [
        a("Geração rápida"),
        a("Conversão em OS"),
        a("Histórico de orçamentos"),
        s("Aprovação pelo cliente"),
        s("Assinatura digital"),
      ],
    },
    {
      id: "estoque",
      title: "Estoque",
      icon: "Boxes",
      items: [
        a("Peças, pneus e lubrificantes"),
        a("Inventário e fornecedores"),
        a("Baixa automática pela OS"),
        s("Lotes e validade"),
        s("Compras"),
      ],
    },
    {
      id: "financeiro",
      title: "Financeiro",
      icon: "Wallet",
      items: [
        a("Caixa e fluxo de caixa"),
        a("Contas a pagar e a receber"),
        a("Comissão"),
        s("PIX e cartão integrados"),
        s("Parcelamentos"),
        s("Controle de inadimplência"),
      ],
    },
    {
      id: "equipe",
      title: "Equipe",
      icon: "UserCog",
      items: [
        a("Mecânicos, lavadores e técnicos"),
        a("Atendimentos realizados"),
        s("Escalas e metas"),
        s("Comissão e produtividade"),
      ],
    },
    {
      id: "especialidade",
      title: "Recursos por especialidade",
      icon: "Wrench",
      items: [
        s("Oficina: plano de revisão, checklist técnico e garantia"),
        s("Lava jato: planos mensais, assinaturas e pacotes"),
        s("Estética: polimento, vitrificação e histórico fotográfico"),
        s("Funilaria: controle por etapas, fotos e materiais"),
        s("Borracharia: rodízio, balanceamento e vida útil dos pneus"),
      ],
    },
  ],
  premium: [
    {
      id: "portal",
      title: "Portal do cliente",
      icon: "Globe",
      items: [
        a("Acompanhamento da OS em tempo real"),
        a("Aprovação de orçamento"),
        a("Histórico do veículo"),
        a("Agendamento online"),
        s("Pagamentos online"),
      ],
    },
    {
      id: "ia",
      title: "Inteligência artificial",
      icon: "Bot",
      items: [
        a("Lembrete automático de revisões"),
        a("Sugestão de serviços"),
        s("Previsão de manutenção preventiva"),
        s("Previsão de estoque"),
        s("Chat inteligente"),
      ],
    },
    {
      id: "marketing",
      title: "Marketing (CRM)",
      icon: "Megaphone",
      items: [
        a("WhatsApp, SMS e e-mail"),
        a("Lembrete de troca de óleo e revisão periódica"),
        s("Clientes inativos"),
        s("Fidelidade e cashback"),
      ],
    },
    {
      id: "unidades",
      title: "Múltiplas unidades",
      icon: "Building2",
      items: [
        s("Gestão centralizada e comparativo entre filiais"),
        s("Transferência de estoque"),
        s("Franquias"),
      ],
    },
    {
      id: "app-mecanico",
      title: "Painel do mecânico",
      icon: "Smartphone",
      items: [
        s("Apontamento de tempo por serviço"),
        s("Andamento dos serviços"),
        s("Produtividade da equipe"),
      ],
    },
  ],
  dashboards: [
    "Faturamento e lucro",
    "Ordens de serviço abertas e concluídas",
    "Ticket médio",
    "Tempo médio de reparo",
    "Serviços mais realizados",
    "Peças mais vendidas",
    "Estoque",
    "Fluxo de caixa",
    "Clientes recorrentes",
    "Produtividade dos mecânicos",
    "Garantias",
    "Índice de retorno por defeito",
  ],
  integrations: [
    { label: "WhatsApp", icon: "MessageCircle" },
    { label: "PIX", icon: "Wallet" },
    { label: "Cartões", icon: "CreditCard" },
    { label: "NFS-e / NFC-e", icon: "FileText" },
    { label: "Catálogo de peças", icon: "Boxes" },
    { label: "Fornecedores", icon: "Truck" },
    { label: "Impressoras", icon: "Receipt" },
    { label: "Leitor de código de barras", icon: "QrCode" },
    { label: "Contabilidade / ERP", icon: "Layers" },
  ],
  differentials: [
    "Ordem de serviço totalmente digital com checklist e fotos",
    "Aprovação de orçamento pelo celular via WhatsApp ou portal",
    "Histórico completo do veículo, independente do proprietário",
    "Controle automático de estoque vinculado à OS",
    "IA para manutenção preventiva e lembretes automáticos",
    "Aplicativo para o cliente acompanhar o serviço em tempo real",
    "Business Intelligence (BI) operacional e financeiro",
    "Planos recorrentes (lava jato, revisões e manutenção preventiva)",
    "Gestão de múltiplas unidades e franquias",
    "Painel do mecânico com apontamento de tempo e produtividade",
  ],
};

const COMERCIO: SegmentExtras = {
  intro:
    "Um ERP completo para o varejo — do PDV ao estoque, das compras ao CRM. Da pequena loja às grandes redes, supermercados, farmácias e distribuidoras.",
  groups: [
    {
      id: "pdv",
      title: "PDV (frente de caixa)",
      icon: "CreditCard",
      items: [
        a("Venda rápida"),
        a("PIX, cartão e dinheiro"),
        a("Trocas, devoluções e cancelamentos"),
        a("Abertura, fechamento e controle por operador"),
        s("Leitura por código de barras e QR Code"),
        s("Crediário, vale-presente e cashback"),
        s("Fidelidade e sangria / suprimento"),
      ],
    },
    {
      id: "produtos",
      title: "Cadastro de produtos",
      icon: "Tag",
      items: [
        a("Produtos com preço e categorias"),
        a("Código de barras e SKU"),
        a("Marca, categoria e fotos"),
        s("Variações (cor, tamanho, modelo)"),
        s("Kits, combos e produtos compostos"),
        s("NCM, CST e CFOP"),
      ],
    },
    {
      id: "estoque",
      title: "Gestão de estoque",
      icon: "Boxes",
      items: [
        a("Entrada, saída e inventário"),
        a("Estoque mínimo e alertas"),
        s("Estoque por loja e depósito"),
        s("Transferências, perdas e avarias"),
        s("Validade, lotes e reserva de estoque"),
        s("Separação, expedição e auditoria"),
      ],
    },
    {
      id: "compras",
      title: "Compras e fornecedores",
      icon: "Truck",
      items: [
        a("Cadastro de fornecedores"),
        a("Histórico de compras"),
        s("Cotação e comparativo de preços"),
        s("Pedido de compra e recebimento"),
        s("Entrada automática no estoque"),
        s("Sugestão automática de reposição"),
      ],
    },
    {
      id: "financeiro",
      title: "Financeiro",
      icon: "Wallet",
      items: [
        a("Caixa e fluxo de caixa"),
        a("Contas a pagar e a receber"),
        s("DRE e centros de custo"),
        s("Boletos e conciliação bancária"),
        s("Cobrança automática e inadimplência"),
      ],
    },
    {
      id: "crm",
      title: "CRM (clientes)",
      icon: "Users",
      items: [
        a("Cadastro e histórico de compras"),
        a("Preferências e observações"),
        s("Limite de crédito e cashback"),
        s("Segmentação e campanhas"),
        s("Aniversariantes e lista de desejos"),
      ],
    },
    {
      id: "vendas",
      title: "Vendas",
      icon: "ShoppingCart",
      items: [
        a("Venda em loja"),
        a("Orçamentos"),
        s("Conversão de orçamento em venda"),
        s("Pedidos, pré-venda e separação"),
        s("Entrega e retirada na loja"),
        s("Venda por vendedor e representante"),
      ],
    },
    {
      id: "equipe",
      title: "Funcionários",
      icon: "UserCog",
      items: [
        a("Cadastro e perfis de acesso"),
        s("Comissão, metas e ranking"),
        s("Escalas e auditoria de atividades"),
      ],
    },
    {
      id: "especialidade",
      title: "Recursos por especialidade",
      icon: "Store",
      items: [
        s("Supermercado: validade, balança, pesáveis e perdas"),
        s("Farmácia: lotes, controlados, convênios e alertas"),
        s("Atacado / distribuidora: preço por quantidade e romaneio"),
        s("Autopeças: busca por veículo, compatibilidade e garantias"),
      ],
    },
  ],
  premium: [
    {
      id: "omnichannel",
      title: "Omnichannel",
      icon: "Globe",
      items: [
        s("Loja física, e-commerce e marketplace"),
        s("WhatsApp, Instagram e catálogo online"),
        s("Venda integrada em todos os canais"),
      ],
    },
    {
      id: "app-cliente",
      title: "Aplicativo do cliente",
      icon: "Smartphone",
      items: [
        s("Catálogo, compras e histórico"),
        s("Cashback, fidelidade e rastreamento"),
        s("Promoções e segunda via de notas"),
      ],
    },
    {
      id: "app-vendedor",
      title: "Aplicativo do vendedor",
      icon: "Smartphone",
      items: [
        s("Consulta de estoque e orçamentos"),
        s("Pedidos, comissão e metas"),
        s("Agenda de visitas"),
      ],
    },
    {
      id: "app-gerente",
      title: "Aplicativo do gerente",
      icon: "BarChart3",
      items: [
        s("Indicadores em tempo real"),
        s("Aprovações e auditorias"),
        s("Estoque, financeiro e alertas"),
      ],
    },
    {
      id: "ia",
      title: "Inteligência artificial",
      icon: "Bot",
      items: [
        s("Previsão de vendas e de ruptura"),
        s("Sugestão automática de compras"),
        s("Curva ABC e precificação inteligente"),
        s("Recomendação de produtos e chatbot"),
        s("Detecção de perdas"),
      ],
    },
    {
      id: "marketing",
      title: "Marketing",
      icon: "Megaphone",
      items: [
        s("WhatsApp, SMS e e-mail"),
        s("Campanhas e clientes inativos"),
        s("Cupons, fidelidade e gift card"),
        s("Programa de indicação"),
      ],
    },
    {
      id: "multiempresa",
      title: "Multiempresa",
      icon: "Building2",
      items: [
        s("Franquias e multilojas"),
        s("Comparativo entre unidades"),
        s("Transferência de estoque"),
        s("Centralização financeira por CNPJ"),
      ],
    },
  ],
  dashboards: [
    "Faturamento diário e mensal",
    "Ticket médio e margem de lucro",
    "Produtos mais e menos vendidos",
    "Curva ABC e giro de estoque",
    "Lucro líquido e fluxo de caixa",
    "Ruptura de estoque",
    "Produtos próximos do vencimento",
    "Perdas e inadimplência",
    "Clientes ativos, recorrentes e novos",
    "Conversão de orçamentos",
    "Ranking de vendedores e comissão",
    "Desempenho por loja e comparativo entre filiais",
    "Horários de maior movimento",
    "Rentabilidade por categoria e fornecedor",
  ],
  integrations: [
    { label: "PIX", icon: "Wallet" },
    { label: "TEF e maquininhas", icon: "CreditCard" },
    { label: "NFC-e / NF-e", icon: "FileText" },
    { label: "WhatsApp", icon: "MessageCircle" },
    { label: "Instagram / Facebook Shop", icon: "Globe" },
    { label: "Marketplaces e e-commerce", icon: "ShoppingCart" },
    { label: "Balanças", icon: "Scale" },
    { label: "Leitor de código de barras", icon: "QrCode" },
    { label: "Impressoras térmicas e etiquetas", icon: "Receipt" },
    { label: "ERP contábil e bancos", icon: "Layers" },
    { label: "Transportadoras", icon: "Truck" },
  ],
  differentials: [
    "Plataforma omnichannel integrada (loja, e-commerce, marketplaces e redes sociais)",
    "IA para prever demanda, sugerir compras e ajustar preços",
    "Controle avançado de estoque com previsão de ruptura e excesso",
    "CRM com fidelidade, cashback, gift card e campanhas automatizadas",
    "BI em tempo real com indicadores financeiros, comerciais e operacionais",
    "Apps completos para clientes, vendedores e gestores",
    "Gestão de múltiplas empresas, lojas e franquias",
    "Auditoria completa de operações e usuários",
    "Automação de compras baseada no giro e sazonalidade",
    "Controle de perdas, validade, lotes e inventários",
    "Integração com pagamentos, emissão fiscal, logística e venda online",
  ],
};

const HOTELARIA: SegmentExtras = {
  intro:
    "Um PMS completo para qualquer tipo de hospedagem — da reserva ao check-out, da governança ao financeiro. Da pousada pequena às redes hoteleiras.",
  groups: [
    {
      id: "reservas",
      title: "Gestão de reservas",
      icon: "Calendar",
      items: [
        a("Reserva presencial e por telefone"),
        a("Alterações e cancelamentos"),
        a("Bloqueio de quartos"),
        s("Reserva online e confirmação automática"),
        s("Reservas de grupos e lista de espera"),
        s("Overbooking controlado"),
      ],
    },
    {
      id: "quartos",
      title: "Gestão de quartos",
      icon: "Bed",
      items: [
        a("Cadastro de quartos e tipos de acomodação"),
        a("Status em tempo real (livre, ocupado, reservado)"),
        s("Em limpeza, manutenção e fora de operação"),
        s("Fotos e equipamentos do quarto"),
      ],
    },
    {
      id: "checkin",
      title: "Check-in e check-out",
      icon: "KeyRound",
      items: [
        a("Check-in e check-out na recepção"),
        s("Pré check-in online e check-out expresso"),
        s("Digitalização de documentos"),
        s("Assinatura eletrônica e emissão de nota"),
        s("Consumo integrado na conta"),
      ],
    },
    {
      id: "hospedes",
      title: "Hóspedes",
      icon: "Users",
      items: [
        a("Cadastro completo e histórico de hospedagens"),
        a("Preferências e observações"),
        s("Documentos e acompanhantes"),
        s("Empresas conveniadas e fidelidade"),
      ],
    },
    {
      id: "financeiro",
      title: "Financeiro",
      icon: "Wallet",
      items: [
        a("Caixa e fluxo de caixa"),
        a("Contas a pagar e a receber"),
        a("Diárias e pacotes"),
        s("PIX e cartão integrados"),
        s("Cobrança recorrente e centros de custo"),
      ],
    },
    {
      id: "housekeeping",
      title: "Governança (housekeeping)",
      icon: "Sparkles",
      items: [
        a("Controle de limpeza e camareiras"),
        a("Checklists e prioridades por quarto"),
        s("Produtos utilizados e tempo de limpeza"),
        s("Histórico por quarto"),
      ],
    },
    {
      id: "manutencao",
      title: "Manutenção",
      icon: "Wrench",
      items: [
        a("Ordens de serviço"),
        s("Preventiva e corretiva"),
        s("Equipamentos e quartos"),
        s("Histórico de manutenções"),
      ],
    },
    {
      id: "consumo",
      title: "Consumo (frigobar e serviços)",
      icon: "CupSoda",
      items: [
        s("Frigobar e room service"),
        s("Restaurante, bar e lavanderia"),
        s("Spa e passeios"),
        s("Consumo automático na conta do hóspede"),
      ],
    },
    {
      id: "especialidade",
      title: "Recursos por tipo de hospedagem",
      icon: "Hotel",
      items: [
        s("Resort: pacotes, recreação, atividades e excursões"),
        s("Pousada: pacotes de temporada e café da manhã"),
        s("Motel: controle por período e consumo em tempo real"),
        s("Flat: proprietários, locações e rateio de receitas"),
      ],
    },
  ],
  premium: [
    {
      id: "portal",
      title: "Portal do hóspede",
      icon: "Globe",
      items: [
        s("Reservar hospedagem e check-in online"),
        s("Check-out online e pagamentos"),
        s("Solicitação de serviços e chat"),
        s("Avaliações e histórico"),
      ],
    },
    {
      id: "app-equipe",
      title: "Aplicativo da equipe",
      icon: "Smartphone",
      items: [
        s("Governança, manutenção e recepção"),
        s("Ordens de serviço"),
        s("Comunicação interna"),
      ],
    },
    {
      id: "ia",
      title: "Inteligência artificial",
      icon: "Bot",
      items: [
        s("Precificação dinâmica e previsão de ocupação"),
        s("Sugestão de tarifas e de demanda"),
        s("Chatbot para reservas"),
        s("Recomendação de upgrades e pacotes"),
      ],
    },
    {
      id: "crm",
      title: "CRM",
      icon: "Megaphone",
      items: [
        s("Fidelidade, cashback e cupons"),
        s("Aniversariantes e clientes VIP"),
        s("Campanhas por WhatsApp e e-mail"),
      ],
    },
    {
      id: "eventos",
      title: "Gestão de eventos",
      icon: "CalendarCheck",
      items: [
        s("Salões e auditórios"),
        s("Reservas corporativas e coffee break"),
        s("Casamentos e congressos"),
      ],
    },
    {
      id: "multiunidades",
      title: "Multiunidades",
      icon: "Building2",
      items: [
        s("Cadeias hoteleiras e franquias"),
        s("Comparativo entre hotéis"),
        s("Gestão centralizada"),
      ],
    },
  ],
  dashboards: [
    "Taxa de ocupação",
    "ADR (diária média) e RevPAR",
    "Receita por hóspede e por quarto",
    "Check-ins e check-outs",
    "Reservas futuras e cancelamentos",
    "Tempo médio de permanência",
    "Consumo médio e faturamento",
    "Fluxo de caixa",
    "Avaliações dos hóspedes",
    "Quartos em manutenção e em limpeza",
    "Produtividade da equipe",
    "Receita por canal de venda",
  ],
  integrations: [
    { label: "Booking.com / Airbnb / Expedia", icon: "Globe" },
    { label: "Decolar", icon: "Globe" },
    { label: "Channel Manager", icon: "Layers" },
    { label: "PIX", icon: "Wallet" },
    { label: "Cartões", icon: "CreditCard" },
    { label: "NFS-e", icon: "FileText" },
    { label: "Fechaduras eletrônicas", icon: "KeyRound" },
    { label: "WhatsApp", icon: "MessageCircle" },
    { label: "Google Hotel / Maps", icon: "MapPin" },
    { label: "Assinatura eletrônica", icon: "FileSignature" },
    { label: "ERP contábil", icon: "Layers" },
  ],
  differentials: [
    "PMS completo para qualquer tipo de hospedagem",
    "Integração com canais de reservas (Channel Manager) sem overbooking",
    "IA para precificação dinâmica, ocupação e upgrades",
    "Check-in e check-out totalmente digitais",
    "Portal e app do hóspede para reservas, pagamentos e serviços",
    "Hospedagem, governança, manutenção, financeiro e eventos integrados",
    "BI em tempo real com indicadores operacionais e financeiros",
    "Gestão centralizada de redes e franquias",
    "CRM com fidelização e campanhas automatizadas",
    "Automação do ciclo da hospedagem, da reserva ao pós-venda",
  ],
};

const EDUCACAO: SegmentExtras = {
  intro:
    "Gestão escolar e de cursos — do cadastro de alunos às mensalidades, turmas e frequência. Da escola pequena às instituições com várias turmas.",
  groups: [
    {
      id: "alunos",
      title: "Cadastro de alunos",
      icon: "Users",
      items: [
        a("Cadastro completo e responsáveis"),
        a("Histórico e observações"),
        a("Campos do segmento"),
        s("Documentos e anexos"),
        s("Portal do aluno / responsável"),
      ],
    },
    {
      id: "turmas",
      title: "Turmas",
      icon: "GraduationCap",
      items: [
        a("Cadastro de turmas"),
        a("Capacidade e turno"),
        a("Professor responsável"),
        s("Grade horária completa"),
        s("Transferência entre turmas"),
      ],
    },
    {
      id: "matriculas",
      title: "Matrículas",
      icon: "ClipboardList",
      items: [
        a("Matrícula por turma"),
        a("Status ativo / trancado"),
        a("Histórico por aluno"),
        s("Rematrícula automática"),
        s("Lista de espera"),
      ],
    },
    {
      id: "frequencia",
      title: "Frequência",
      icon: "CalendarCheck",
      items: [
        a("Chamada por turma e data"),
        a("Registro de presença e falta"),
        s("Justificativas e anexos"),
        s("Relatório de frequência"),
        s("Alertas de evasão"),
      ],
    },
    {
      id: "agenda",
      title: "Agenda de aulas",
      icon: "Calendar",
      items: [
        a("Aulas e horários por turma"),
        a("Agenda por professor"),
        s("Substituições e reposições"),
        s("Calendário escolar"),
      ],
    },
    {
      id: "financeiro",
      title: "Financeiro",
      icon: "Wallet",
      items: [
        a("Mensalidades e matrículas"),
        a("Contas a pagar e a receber"),
        a("Controle de inadimplência"),
        s("Cobrança recorrente"),
        s("Bolsas e descontos"),
      ],
    },
    {
      id: "professores",
      title: "Professores e equipe",
      icon: "UserCog",
      items: [
        a("Cadastro de professores"),
        a("Turmas vinculadas"),
        s("Escalas e substituições"),
        s("Produtividade"),
      ],
    },
  ],
  premium: [
    {
      id: "portal",
      title: "Portal do aluno / responsável",
      icon: "Globe",
      items: [
        a("Frequência e mensalidades"),
        a("Turmas matriculadas"),
        s("Boletim completo"),
        s("Comunicados"),
      ],
    },
    {
      id: "ia",
      title: "Inteligência artificial",
      icon: "Bot",
      items: [
        s("Alertas de evasão"),
        s("Sugestão de rematrícula"),
        s("Resumo de desempenho"),
      ],
    },
    {
      id: "comunicacao",
      title: "Comunicação",
      icon: "MessageCircle",
      items: [
        s("WhatsApp e e-mail para responsáveis"),
        s("Comunicados por turma"),
        s("Lembretes de mensalidade"),
      ],
    },
  ],
  dashboards: [
    "Alunos ativos e novos alunos",
    "Turmas e vagas disponíveis",
    "Matrículas do período",
    "Frequência média por turma",
    "Inadimplência",
    "Faturamento de mensalidades",
    "Professores e turmas vinculadas",
  ],
  integrations: [
    { label: "WhatsApp", icon: "MessageCircle" },
    { label: "E-mail", icon: "Mail" },
    { label: "PIX", icon: "Wallet" },
    { label: "Cartões", icon: "CreditCard" },
    { label: "Google Agenda", icon: "Calendar" },
    { label: "Contabilidade / ERP", icon: "Layers" },
  ],
  differentials: [
    "Turmas, matrículas e frequência integrados ao financeiro",
    "Cadastro de alunos com responsáveis e campos do segmento",
    "Controle de mensalidades e inadimplência por turma",
    "Chamada digital por turma e data",
    "Relatórios de matrículas, frequência e receita",
  ],
};

const PET: SegmentExtras = {
  intro:
    "Uma plataforma completa para o mercado pet — clínica veterinária, pet shop, banho e tosa, hotel e creche em um único ERP. Do pet shop às redes e franquias.",
  groups: [
    {
      id: "tutores",
      title: "Cadastro de tutores",
      icon: "Users",
      items: [
        a("Cadastro completo e contatos"),
        a("Pets vinculados e histórico"),
        a("Observações e convênios"),
        s("Documentos e endereços"),
        s("Histórico financeiro"),
      ],
    },
    {
      id: "pets",
      title: "Cadastro dos pets",
      icon: "PawPrint",
      items: [
        a("Espécie, raça, sexo e peso"),
        a("Alergias e restrições"),
        s("Microchip, pedigree e castração"),
        s("Fotos e plano de saúde"),
      ],
    },
    {
      id: "agenda",
      title: "Agenda inteligente",
      icon: "Calendar",
      items: [
        a("Consultas, banho, tosa e vacinação"),
        a("Agenda por profissional"),
        a("Reagendamento"),
        s("Cirurgias, hospedagem e adestramento"),
        s("Confirmação automática e lista de espera"),
      ],
    },
    {
      id: "prontuario",
      title: "Prontuário veterinário",
      icon: "ClipboardList",
      items: [
        a("Anamnese e evolução clínica"),
        a("Histórico completo e anexos"),
        s("Diagnósticos e prescrições"),
        s("Exames, internações e cirurgias"),
        s("Fotos"),
      ],
    },
    {
      id: "vacinacao",
      title: "Vacinação",
      icon: "Syringe",
      items: [
        a("Histórico de vacinas"),
        s("Calendário vacinal e carteira digital"),
        s("Alertas automáticos"),
        s("Campanhas de vacinação"),
      ],
    },
    {
      id: "cirurgias",
      title: "Cirurgias",
      icon: "HeartPulse",
      items: [
        s("Agendamento e equipe médica"),
        s("Checklist pré-operatório"),
        s("Evolução, pós-operatório e alta"),
      ],
    },
    {
      id: "internacao",
      title: "Internação",
      icon: "Bed",
      items: [
        s("Leitos e evolução"),
        s("Medicações e alimentação"),
        s("Procedimentos e monitoramento"),
        s("Alta"),
      ],
    },
    {
      id: "banho-tosa",
      title: "Banho e tosa",
      icon: "Scissors",
      items: [
        a("Agendamento e pacotes"),
        a("Preferências do tutor"),
        s("Produtos utilizados"),
        s("Fotos antes e depois"),
      ],
    },
    {
      id: "hotel-creche",
      title: "Hotel e creche",
      icon: "Dog",
      items: [
        s("Reservas, check-in e check-out"),
        s("Alimentação, passeios e medicamentos"),
        s("Relatórios diários e fotos para tutores"),
      ],
    },
    {
      id: "estoque",
      title: "Estoque",
      icon: "Boxes",
      items: [
        a("Produtos, rações e acessórios"),
        a("Entrada, saída e inventário"),
        s("Medicamentos e vacinas com lote e validade"),
        s("Compras e fornecedores"),
      ],
    },
    {
      id: "financeiro",
      title: "Financeiro",
      icon: "Wallet",
      items: [
        a("Caixa e fluxo de caixa"),
        a("Contas a pagar e a receber"),
        s("PIX, cartão e convênios"),
        s("Planos mensais e cobrança recorrente"),
      ],
    },
    {
      id: "especialidade",
      title: "Recursos por especialidade",
      icon: "Stethoscope",
      items: [
        s("Clínica: prontuário, exames e prescrição digital"),
        s("Hospital: internação, UTI, emergência e centro cirúrgico"),
        s("Pet shop: PDV, fidelidade e catálogo"),
        s("Adestramento: planos, cronograma e evolução"),
      ],
    },
  ],
  premium: [
    {
      id: "app-tutor",
      title: "Aplicativo do tutor",
      icon: "Smartphone",
      items: [
        s("Agendamentos e carteira de vacinação"),
        s("Prontuário, receitas e exames"),
        s("Pagamentos e chat"),
        s("Fotos e rastreamento da hospedagem"),
        s("Lembretes automáticos"),
      ],
    },
    {
      id: "app-equipe",
      title: "Aplicativo da equipe",
      icon: "Smartphone",
      items: [
        s("Agenda, prontuário e evolução"),
        s("Internações e checklists"),
        s("Fotos e ordens de serviço"),
      ],
    },
    {
      id: "ia",
      title: "Inteligência artificial",
      icon: "Bot",
      items: [
        s("Lembretes de vacinas e consultas"),
        s("Sugestão de protocolos clínicos"),
        s("Resumo inteligente do prontuário"),
        s("Previsão de retorno e sugestão de produtos"),
        s("Chatbot e alertas de medicamentos"),
      ],
    },
    {
      id: "crm",
      title: "Marketing (CRM)",
      icon: "Megaphone",
      items: [
        s("WhatsApp, SMS e e-mail"),
        s("Aniversário do pet e campanhas de vacinação"),
        s("Clientes inativos, cupons e fidelidade"),
        s("Cashback"),
      ],
    },
    {
      id: "multiunidades",
      title: "Multiunidades",
      icon: "Building2",
      items: [
        s("Redes de clínicas e franquias"),
        s("Comparativo entre unidades"),
        s("Gestão centralizada"),
      ],
    },
  ],
  dashboards: [
    "Consultas, banhos e tosas realizados",
    "Vacinas aplicadas e cirurgias",
    "Internações e pets ativos",
    "Novos clientes e taxa de retorno",
    "Ticket médio e faturamento",
    "Fluxo de caixa",
    "Produtos mais vendidos e estoque",
    "Medicamentos próximos do vencimento",
    "Profissionais mais produtivos",
    "Ocupação do hotel e da creche",
    "Avaliações dos clientes",
    "Rentabilidade por serviço",
  ],
  integrations: [
    { label: "PIX", icon: "Wallet" },
    { label: "Cartões", icon: "CreditCard" },
    { label: "NFS-e", icon: "FileText" },
    { label: "Laboratórios veterinários", icon: "Syringe" },
    { label: "WhatsApp", icon: "MessageCircle" },
    { label: "Google Agenda", icon: "Calendar" },
    { label: "Google Maps", icon: "MapPin" },
    { label: "Assinatura eletrônica", icon: "FileSignature" },
    { label: "Microchip", icon: "Fingerprint" },
    { label: "ERP contábil", icon: "Layers" },
  ],
  differentials: [
    "Plataforma que integra clínica, pet shop, banho e tosa, hotel e creche",
    "Prontuário veterinário com exames, receitas e evolução clínica",
    "App do tutor com vacinação digital, agendamentos e acompanhamento em tempo real",
    "IA para lembretes, protocolos clínicos, fidelização e previsão de retornos",
    "CRM com campanhas personalizadas e programa de fidelidade",
    "BI em tempo real com indicadores clínicos, financeiros e operacionais",
    "Estoque de medicamentos, vacinas e rações com lote e validade",
    "Gestão de múltiplas unidades e franquias",
    "Comunicação automatizada via WhatsApp, e-mail e push",
    "ERP especializado para tutores, equipe veterinária e gestores",
  ],
};

const EVENTOS: SegmentExtras = {
  intro:
    "Gestão completa do evento — do primeiro contato ao pós-evento. CRM, orçamento, contrato, financeiro, fornecedores, equipes e materiais integrados para cerimonialistas, buffets, casas de festas e produtoras.",
  groups: [
    {
      id: "eventos",
      title: "Gestão de eventos",
      icon: "PartyPopper",
      items: [
        a("Cadastro de eventos e tipo"),
        a("Cliente, data, horário e local"),
        a("Responsáveis e status"),
        a("Observações"),
        s("Número de convidados"),
        s("Checklist e cronograma do evento"),
      ],
    },
    {
      id: "agenda",
      title: "Agenda",
      icon: "CalendarHeart",
      items: [
        a("Calendário de eventos"),
        a("Reuniões e visitas técnicas"),
        s("Degustações, ensaios e montagens"),
        s("Desmontagens e bloqueio de datas"),
        s("Alertas automáticos"),
      ],
    },
    {
      id: "crm",
      title: "CRM de clientes",
      icon: "Users",
      items: [
        a("Cadastro completo"),
        a("Histórico de eventos"),
        s("Preferências e orçamentos enviados"),
        s("Contratos e comunicação"),
        s("Histórico de pagamentos"),
      ],
    },
    {
      id: "orcamentos",
      title: "Orçamentos",
      icon: "FileText",
      items: [
        a("Criação de propostas"),
        s("Pacotes, serviços e produtos"),
        s("Adicionais e personalização"),
        s("Aprovação online"),
        s("Conversão em contrato"),
      ],
    },
    {
      id: "contratos",
      title: "Contratos",
      icon: "FileSignature",
      items: [
        s("Contratos digitais e modelos personalizados"),
        s("Assinatura eletrônica"),
        s("Cláusulas, aditivos e vencimentos"),
      ],
    },
    {
      id: "financeiro",
      title: "Financeiro",
      icon: "Wallet",
      items: [
        a("Contas a pagar e a receber"),
        a("Fluxo de caixa"),
        s("Parcelamentos, PIX, cartão e boletos"),
        s("Inadimplência, comissão e custos por evento"),
      ],
    },
    {
      id: "fornecedores",
      title: "Fornecedores",
      icon: "Truck",
      items: [
        a("Cadastro e categorias"),
        s("Contratos, valores e disponibilidade"),
        s("Avaliações e histórico"),
      ],
    },
    {
      id: "equipes",
      title: "Equipes",
      icon: "UsersRound",
      items: [
        a("Funcionários e freelancers"),
        s("Escalas, funções e checklists"),
        s("Produtividade e pagamentos"),
      ],
    },
    {
      id: "materiais",
      title: "Materiais e patrimônio",
      icon: "Package",
      items: [
        a("Cadastro de materiais e equipamentos"),
        s("Mobiliário, decoração e estruturas"),
        s("Estoque, reservas e manutenção"),
        s("Inventário"),
      ],
    },
    {
      id: "especialidade",
      title: "Recursos por tipo de negócio",
      icon: "Sparkles",
      items: [
        s("Casamentos: convidados, RSVP, mesas e cerimônia"),
        s("Buffet: cardápio, ficha técnica e produção"),
        s("Fotografia e filmagem: pacotes, galeria e entrega"),
        s("Corporativos: inscrições, credenciamento e certificados"),
      ],
    },
  ],
  premium: [
    {
      id: "portal",
      title: "Portal do cliente",
      icon: "Globe",
      items: [
        s("Acompanhar evento e cronograma"),
        s("Aprovar orçamento e ver contratos"),
        s("Pagamentos e escolha de opções"),
        s("Enviar documentos e chat"),
      ],
    },
    {
      id: "app-equipe",
      title: "Aplicativo da equipe",
      icon: "Smartphone",
      items: [
        s("Agenda e eventos atribuídos"),
        s("Checklist e tarefas"),
        s("Fotos, ocorrências e comunicação interna"),
      ],
    },
    {
      id: "convidados",
      title: "Gestão de convidados",
      icon: "QrCode",
      items: [
        s("Cadastro e confirmação de presença (RSVP)"),
        s("QR Code e check-in"),
        s("Lista de convidados e controle de acesso"),
      ],
    },
    {
      id: "ia",
      title: "Inteligência artificial",
      icon: "Bot",
      items: [
        s("Cronogramas automáticos"),
        s("Sugestão de fornecedores e previsão de custos"),
        s("Análise de orçamento e geração de propostas"),
        s("Organização de tarefas e assistente virtual"),
      ],
    },
    {
      id: "marketing",
      title: "Marketing",
      icon: "Megaphone",
      items: [
        s("Campanhas por WhatsApp e e-mail"),
        s("Leads, funil comercial e follow-up"),
        s("Pesquisa de satisfação e indicações"),
      ],
    },
    {
      id: "multiempresa",
      title: "Multiempresa",
      icon: "Building2",
      items: [
        s("Filiais e equipes"),
        s("Comparativo entre unidades"),
        s("Gestão centralizada"),
      ],
    },
  ],
  dashboards: [
    "Eventos agendados, em andamento e concluídos",
    "Faturamento e lucro por evento",
    "Custos por evento e ticket médio",
    "Conversão de propostas",
    "Clientes novos e recorrentes",
    "Pagamentos pendentes",
    "Fornecedores mais usados",
    "Rentabilidade por serviço",
    "Ocupação da agenda",
    "Produtividade da equipe",
    "Avaliações dos clientes",
  ],
  integrations: [
    { label: "PIX", icon: "Wallet" },
    { label: "Cartões", icon: "CreditCard" },
    { label: "Bancos", icon: "Landmark" },
    { label: "NFS-e", icon: "FileText" },
    { label: "WhatsApp", icon: "MessageCircle" },
    { label: "Google Agenda", icon: "Calendar" },
    { label: "Google Drive", icon: "FolderOpen" },
    { label: "Google Maps", icon: "MapPin" },
    { label: "Assinatura eletrônica", icon: "FileSignature" },
    { label: "Plataformas de convite", icon: "Mail" },
    { label: "Redes sociais", icon: "Share2" },
  ],
  differentials: [
    "Gestão completa do evento do primeiro contato até o pós-evento",
    "CRM + orçamento + contrato + financeiro totalmente integrados",
    "Portal do cliente para acompanhar todo o planejamento",
    "Controle de convidados com RSVP e QR Code",
    "Gestão de fornecedores e equipes em tempo real",
    "IA para cronogramas, propostas, checklists e previsão de custos",
    "App da equipe de campo para tarefas durante o evento",
    "Controle de materiais, equipamentos e patrimônio",
    "BI com lucratividade por evento e indicadores operacionais",
    "Automação de comunicação com clientes e fornecedores",
    "Gestão de múltiplos eventos simultâneos sem perder controle",
  ],
};

const ORGANIZACOES: SegmentExtras = {
  intro:
    "Plataforma completa para gestão administrativa, financeira e operacional de igrejas, ONGs, associações e fundações — do cadastro de membros à prestação de contas.",
  groups: [
    {
      id: "membros",
      title: "Cadastro de membros / participantes",
      icon: "Users",
      items: [
        a("Cadastro completo com contatos"),
        a("Endereço e observações"),
        s("Histórico de participação"),
        s("Grupos, departamentos e documentos"),
        s("Anexos"),
      ],
    },
    {
      id: "grupos",
      title: "Grupos e departamentos",
      icon: "UsersRound",
      items: [
        a("Ministérios, equipes e departamentos"),
        s("Células e comunidades"),
        s("Líderes responsáveis e participantes"),
        s("Atividades e frequência"),
      ],
    },
    {
      id: "eventos",
      title: "Gestão de eventos",
      icon: "CalendarCheck",
      items: [
        a("Cadastro de eventos"),
        a("Reuniões e palestras"),
        s("Cultos, conferências e cursos"),
        s("Ações sociais, inscrições e check-in"),
        s("Lista de participantes"),
      ],
    },
    {
      id: "agenda",
      title: "Agenda",
      icon: "Calendar",
      items: [
        a("Calendário geral"),
        s("Reservas de salas e equipamentos"),
        s("Responsáveis e lembretes automáticos"),
      ],
    },
    {
      id: "financeiro",
      title: "Financeiro",
      icon: "Wallet",
      items: [
        a("Caixa e fluxo de caixa"),
        a("Contas a pagar e a receber"),
        s("Centros de custo e orçamento anual"),
        s("Relatórios financeiros"),
      ],
    },
    {
      id: "doacoes",
      title: "Doações e contribuições",
      icon: "HeartHandshake",
      items: [
        a("Registro de doações e entradas"),
        s("Contribuições recorrentes"),
        s("PIX, cartão e transferências"),
        s("Comprovantes e histórico por pessoa"),
        s("Campanhas específicas"),
      ],
    },
    {
      id: "voluntarios",
      title: "Gestão de voluntários",
      icon: "HandHeart",
      items: [
        a("Cadastro de voluntários"),
        s("Disponibilidade, escalas e funções"),
        s("Treinamentos e histórico de participação"),
      ],
    },
    {
      id: "patrimonio",
      title: "Patrimônio",
      icon: "Package",
      items: [
        a("Cadastro de bens e equipamentos"),
        s("Móveis, veículos e salas"),
        s("Inventário, manutenção e responsáveis"),
      ],
    },
    {
      id: "documentos",
      title: "Documentos",
      icon: "FolderOpen",
      items: [
        s("Contratos, atas e certificados"),
        s("Regulamentos e relatórios"),
        s("Arquivos digitais e controle de acesso"),
      ],
    },
    {
      id: "especialidade",
      title: "Recursos por tipo de organização",
      icon: "Sparkles",
      items: [
        s("Igrejas: escalas, ministérios e visitantes"),
        s("ONGs: beneficiários, projetos e indicadores sociais"),
        s("Associações: mensalidades, assembleias e votações"),
      ],
    },
  ],
  premium: [
    {
      id: "app-membros",
      title: "Aplicativo dos membros",
      icon: "Smartphone",
      items: [
        s("Agenda, eventos e comunicados"),
        s("Inscrições e doações"),
        s("Documentos, solicitações e comunicação"),
      ],
    },
    {
      id: "portal-admin",
      title: "Portal administrativo",
      icon: "LayoutDashboard",
      items: [
        s("Gestão completa e relatórios"),
        s("Financeiro, pessoas e eventos"),
        s("Documentos e indicadores"),
      ],
    },
    {
      id: "comunicacao",
      title: "Comunicação integrada",
      icon: "MessageCircle",
      items: [
        s("WhatsApp, e-mail e SMS"),
        s("Notificações push e comunicados"),
        s("Pesquisas e campanhas"),
      ],
    },
    {
      id: "ia",
      title: "Inteligência artificial",
      icon: "Bot",
      items: [
        s("Resumo de relatórios e organização de documentos"),
        s("Assistente administrativo"),
        s("Análise financeira e previsão de receitas"),
        s("Sugestão de comunicação e automação de respostas"),
      ],
    },
    {
      id: "projetos",
      title: "Gestão de projetos sociais",
      icon: "Target",
      items: [
        s("Cadastro de projetos com objetivos e metas"),
        s("Cronograma, equipe e recursos"),
        s("Indicadores e resultados"),
      ],
    },
    {
      id: "multiunidades",
      title: "Multiunidades",
      icon: "Building2",
      items: [
        s("Sedes, filiais e núcleos"),
        s("Comparativos entre unidades"),
        s("Gestão centralizada"),
      ],
    },
  ],
  dashboards: [
    "Número de membros e novos membros",
    "Participação em eventos e frequência",
    "Voluntários ativos",
    "Doações recebidas",
    "Receitas, despesas e saldo financeiro",
    "Projetos ativos e metas alcançadas",
    "Crescimento e engajamento dos participantes",
    "Eventos realizados",
    "Recursos utilizados e patrimônio",
    "Indicadores por unidade",
  ],
  integrations: [
    { label: "PIX", icon: "Wallet" },
    { label: "Bancos", icon: "Landmark" },
    { label: "Cartões", icon: "CreditCard" },
    { label: "WhatsApp", icon: "MessageCircle" },
    { label: "E-mail", icon: "Mail" },
    { label: "Google Agenda", icon: "Calendar" },
    { label: "Google Drive", icon: "FolderOpen" },
    { label: "Assinatura eletrônica", icon: "FileSignature" },
    { label: "Plataformas de pagamento", icon: "CreditCard" },
    { label: "Sistemas contábeis", icon: "Layers" },
  ],
  differentials: [
    "Plataforma completa para gestão administrativa, financeira e operacional",
    "Cadastro inteligente de membros, voluntários e beneficiários",
    "Gestão financeira transparente com relatórios e prestação de contas",
    "App próprio para membros acompanharem eventos, comunicados e contribuições",
    "Gestão de projetos sociais com indicadores de impacto",
    "IA para automatizar tarefas administrativas, relatórios e comunicação",
    "BI com visão completa da organização",
    "Gestão de múltiplas unidades, sedes e equipes",
    "Controle patrimonial e documental completo",
    "Automação de comunicação e engajamento dos participantes",
  ],
};

// Conjunto generico para os demais segmentos (ate serem detalhados como Beleza).
const DEFAULT_EXTRAS: SegmentExtras = {
  intro:
    "Funcionalidades para organizar a operação do seu negócio, com novos recursos chegando continuamente.",
  groups: [
    {
      id: "agenda",
      title: "Agenda",
      icon: "Calendar",
      items: [a("Agenda por profissional"), a("Bloqueio de horários"), a("Reagendamento"), a("Agendamento online")],
    },
    {
      id: "crm",
      title: "Clientes (CRM)",
      icon: "Users",
      items: [a("Histórico completo"), a("Campos do segmento"), a("Observações"), s("Fotos e documentos")],
    },
    {
      id: "financeiro",
      title: "Financeiro",
      icon: "Wallet",
      items: [a("Caixa"), a("Contas a pagar e receber"), a("Fluxo de caixa"), s("Pagamentos integrados")],
    },
  ],
  premium: [
    { id: "ia", title: "Inteligência artificial", icon: "Bot", items: [s("Insights e sugestões"), s("Previsões")] },
    { id: "app", title: "Aplicativo", icon: "Smartphone", items: [s("Acesso pelo celular")] },
  ],
  dashboards: ["Faturamento", "Atendimentos", "Clientes novos e recorrentes", "Ticket médio"],
  integrations: [
    { label: "WhatsApp", icon: "MessageCircle" },
    { label: "PIX", icon: "Wallet" },
    { label: "Cartão", icon: "CreditCard" },
  ],
  differentials: [
    "Plataforma que se adapta ao seu segmento",
    "Dados isolados e seguros",
    "Acesso de qualquer lugar",
  ],
};

const BY_CATEGORY: Partial<Record<SegmentCategory, SegmentExtras>> = {
  beleza: BELEZA,
  alimentacao: ALIMENTACAO,
  saude: SAUDE,
  servicos: SERVICOS,
  automotivo: AUTOMOTIVO,
  comercio: COMERCIO,
  hotelaria: HOTELARIA,
  educacao: EDUCACAO,
  eventos: EVENTOS,
  organizacoes: ORGANIZACOES,
  pet: PET,
};

export function getSegmentExtras(category: SegmentCategory): SegmentExtras {
  return BY_CATEGORY[category] ?? DEFAULT_EXTRAS;
}
