import type { SegmentTemplate } from "./types";

// Sub-nichos de Pet.

const tutorFields = [
  { key: "cpf", label: "CPF", type: "text" as const },
  { key: "endereco", label: "Endereço", type: "text" as const },
  { key: "convenio", label: "Convênio / plano", type: "text" as const },
];

const petFields = [
  { key: "pet", label: "Nome do pet", type: "text" as const },
  { key: "especie", label: "Espécie", type: "select" as const, options: ["Cão", "Gato", "Ave", "Roedor", "Outro"] },
  { key: "raca", label: "Raça", type: "text" as const },
  { key: "peso", label: "Peso (kg)", type: "number" as const },
  { key: "alergias", label: "Alergias / restrições", type: "text" as const },
];

export const petshop: SegmentTemplate = {
  id: "petshop",
  label: "Pet Shop",
  slug: "petshop",
  icon: "PawPrint",
  category: "pet",
  tagline: "PDV, banho e tosa, tutores e estoque.",
  modules: ["clients", "scheduling", "services", "inventory", "financial", "team"],
  terms: {
    customer: "Tutor",
    customer_plural: "Tutores",
    professional: "Profissional",
    professional_plural: "Profissionais",
    service: "Serviço",
    service_plural: "Serviços",
    appointment: "Agendamento",
    appointment_plural: "Agenda",
    inventory: "Produtos / Estoque",
  },
  customerFields: petFields,
  defaultServices: [
    { name: "Banho", price: 50, durationMin: 60 },
    { name: "Banho e tosa", price: 90, durationMin: 90 },
    { name: "Tosa higiênica", price: 45, durationMin: 40 },
  ],
  benefits: [
    "PDV com venda de produtos e serviços",
    "Agenda de banho e tosa por profissional",
    "Cadastro de tutores e pets com histórico",
    "Estoque de rações, medicamentos e acessórios",
    "Fidelidade e cashback — a caminho",
  ],
  faq: [
    { q: "Consigo cadastrar mais de um pet por tutor?", a: "Sim. Cada tutor pode ter vários pets, cada um com o próprio histórico." },
    { q: "Vendo produtos além dos serviços?", a: "Sim. O PDV integra venda de produtos com estoque e serviços de banho e tosa." },
  ],
  seo: {
    title: "Sistema para Pet Shop | PDV, banho e tosa",
    description: "Software para pet shop com PDV, banho e tosa, tutores, pets, estoque e financeiro.",
    keywords: ["sistema para pet shop", "pdv pet shop", "banho e tosa"],
    headline: "O sistema completo do seu pet shop",
    subheadline: "PDV, banho e tosa, tutores, pets, estoque e fidelidade.",
  },
};

export const clinicaVeterinaria: SegmentTemplate = {
  id: "clinica-veterinaria",
  label: "Clínica Veterinária",
  slug: "clinica-veterinaria",
  icon: "Stethoscope",
  category: "pet",
  tagline: "Consultas, prontuário e vacinação.",
  modules: ["clients", "scheduling", "services", "records", "inventory", "financial", "team"],
  terms: {
    customer: "Tutor",
    customer_plural: "Tutores",
    professional: "Veterinário",
    professional_plural: "Veterinários",
    service: "Procedimento",
    service_plural: "Procedimentos",
    appointment: "Consulta",
    appointment_plural: "Consultas",
    records: "Prontuário",
    inventory: "Medicamentos / Estoque",
  },
  customerFields: [...tutorFields, ...petFields],
  defaultServices: [
    { name: "Consulta clínica", price: 150, durationMin: 30 },
    { name: "Vacina V8/V10", price: 80, durationMin: 15 },
    { name: "Exame de sangue", price: 120, durationMin: 0 },
  ],
  benefits: [
    "Prontuário veterinário com evolução e prescrições",
    "Calendário vacinal com alertas automáticos",
    "Agenda de consultas, exames e cirurgias",
    "Estoque de medicamentos e vacinas com validade",
    "Financeiro com convênios e planos",
  ],
  faq: [
    { q: "Tenho prontuário eletrônico?", a: "Sim. Cada pet tem prontuário com anamnese, evolução, exames e prescrições." },
    { q: "Alerto sobre vacinas?", a: "Sim. O calendário vacinal avisa quando a próxima dose está próxima (notificação automática a caminho)." },
  ],
  seo: {
    title: "Sistema para Clínica Veterinária | Prontuário e vacinas",
    description: "Software para clínica veterinária com prontuário, vacinação, agenda, exames, estoque e financeiro.",
    keywords: ["sistema clínica veterinária", "prontuário veterinário", "software veterinário"],
    headline: "O sistema da sua clínica veterinária",
    subheadline: "Prontuário, vacinação, agenda, exames, estoque e financeiro.",
  },
};

export const hospitalVeterinario: SegmentTemplate = {
  id: "hospital-veterinario",
  label: "Hospital Veterinário",
  slug: "hospital-veterinario",
  icon: "HeartPulse",
  category: "pet",
  tagline: "Internação, UTI, cirurgias e emergência.",
  modules: ["clients", "scheduling", "services", "records", "inventory", "financial", "team", "work_orders"],
  terms: {
    customer: "Tutor",
    customer_plural: "Tutores",
    professional: "Veterinário",
    professional_plural: "Veterinários",
    service: "Procedimento",
    service_plural: "Procedimentos",
    appointment: "Atendimento",
    appointment_plural: "Agenda",
    records: "Prontuário",
    work_order: "Internação",
    work_order_plural: "Internações",
    inventory: "Medicamentos / Estoque",
  },
  customerFields: [...tutorFields, ...petFields],
  defaultServices: [
    { name: "Internação (diária)", price: 180, durationMin: 0 },
    { name: "Cirurgia eletiva", price: 800, durationMin: 0 },
    { name: "Emergência / plantão", price: 250, durationMin: 0 },
  ],
  benefits: [
    "Controle de internação com leitos e evolução",
    "Centro cirúrgico com checklist pré-operatório",
    "Emergência e plantão na agenda",
    "Medicações, alimentação e monitoramento por internação",
    "Estoque de medicamentos com lote e validade",
  ],
  faq: [
    { q: "Controlo internações?", a: "Sim. Cada internação tem leito, evolução, medicações e procedimentos organizados." },
    { q: "Agendo cirurgias?", a: "Sim. Cirurgias têm equipe, checklist pré-operatório e evolução pós-operatória." },
  ],
  seo: {
    title: "Sistema para Hospital Veterinário | Internação e cirurgias",
    description: "Software para hospital veterinário com internação, UTI, cirurgias, emergência, prontuário e estoque.",
    keywords: ["sistema hospital veterinário", "internação veterinária", "software UTI pet"],
    headline: "O sistema do seu hospital veterinário",
    subheadline: "Internação, UTI, cirurgias, emergência, prontuário e estoque.",
  },
};

export const banhoTosa: SegmentTemplate = {
  id: "banho-tosa",
  label: "Banho e Tosa",
  slug: "banho-e-tosa",
  icon: "Scissors",
  category: "pet",
  tagline: "Agenda, pacotes e fotos antes/depois.",
  modules: ["clients", "scheduling", "services", "inventory", "financial", "team"],
  terms: {
    customer: "Tutor",
    customer_plural: "Tutores",
    professional: "Tosador",
    professional_plural: "Tosadores",
    service: "Serviço",
    service_plural: "Serviços",
    appointment: "Agendamento",
    appointment_plural: "Agenda",
    inventory: "Produtos / Estoque",
  },
  customerFields: [
    ...petFields,
    { key: "preferencias", label: "Preferências de tosa", type: "text" as const },
  ],
  defaultServices: [
    { name: "Banho P", price: 40, durationMin: 45 },
    { name: "Banho e tosa M", price: 80, durationMin: 90 },
    { name: "Pacote 4 banhos", price: 140, durationMin: 0 },
  ],
  benefits: [
    "Agenda por tosador com confirmação",
    "Pacotes de banho e tosa com controle de uso",
    "Fotos antes e depois por atendimento",
    "Preferências do tutor registradas por pet",
    "Produtos utilizados no serviço",
  ],
  faq: [
    { q: "Guardo fotos antes e depois?", a: "Sim. Cada atendimento pode ter fotos no histórico do pet." },
    { q: "Trabalho com pacotes?", a: "Sim. Você vende pacotes (ex.: 4 banhos) e acompanha o que falta para cada pet." },
  ],
  seo: {
    title: "Sistema para Banho e Tosa | Agenda e pacotes",
    description: "Software para banho e tosa com agenda, pacotes, fotos antes/depois, preferências e financeiro.",
    keywords: ["sistema banho e tosa", "agenda pet grooming", "software tosa"],
    headline: "O sistema do seu banho e tosa",
    subheadline: "Agenda, pacotes, fotos antes/depois, preferências e financeiro.",
  },
};

export const hotelPet: SegmentTemplate = {
  id: "hotel-pet",
  label: "Hotel para Pets",
  slug: "hotel-para-pets",
  icon: "Bed",
  category: "pet",
  tagline: "Reservas, check-in e relatórios diários.",
  modules: ["clients", "scheduling", "services", "financial", "team"],
  terms: {
    customer: "Tutor",
    customer_plural: "Tutores",
    professional: "Cuidador",
    professional_plural: "Cuidadores",
    service: "Diária",
    service_plural: "Diárias",
    appointment: "Reserva",
    appointment_plural: "Reservas",
  },
  customerFields: [...tutorFields, ...petFields],
  defaultServices: [
    { name: "Diária (cão P)", price: 70, durationMin: 0 },
    { name: "Diária (cão G)", price: 100, durationMin: 0 },
    { name: "Diária (gato)", price: 60, durationMin: 0 },
  ],
  benefits: [
    "Reservas com check-in e check-out",
    "Alimentação, medicamentos e passeios registrados",
    "Relatórios diários e fotos para o tutor",
    "Controle de ocupação por baias/leitos",
    "Financeiro com pacotes e diárias",
  ],
  faq: [
    { q: "Envio fotos ao tutor?", a: "Sim. Você registra fotos e relatórios diários no histórico da hospedagem (app do tutor a caminho)." },
    { q: "Registro medicamentos na estadia?", a: "Sim. Cada reserva guarda alimentação, medicamentos e observações do pet." },
  ],
  seo: {
    title: "Sistema para Hotel para Pets | Reservas e relatórios",
    description: "Software para hotel de pets com reservas, check-in, alimentação, medicamentos, fotos e financeiro.",
    keywords: ["sistema hotel pet", "hospedagem cães", "software hotel animal"],
    headline: "O sistema do seu hotel para pets",
    subheadline: "Reservas, check-in, relatórios diários, fotos e financeiro.",
  },
};

export const crechePet: SegmentTemplate = {
  id: "creche-pet",
  label: "Creche para Pets",
  slug: "creche-para-pets",
  icon: "Dog",
  category: "pet",
  tagline: "Planos mensais, check-in e relatórios.",
  modules: ["clients", "scheduling", "services", "financial", "team"],
  terms: {
    customer: "Tutor",
    customer_plural: "Tutores",
    professional: "Monitor",
    professional_plural: "Monitores",
    service: "Plano",
    service_plural: "Planos",
    appointment: "Check-in",
    appointment_plural: "Agenda",
  },
  customerFields: [...petFields],
  defaultServices: [
    { name: "Plano mensal (2x/semana)", price: 380, durationMin: 0 },
    { name: "Plano mensal (5x/semana)", price: 650, durationMin: 0 },
    { name: "Day use (avulso)", price: 65, durationMin: 0 },
  ],
  benefits: [
    "Planos mensais com controle de frequência",
    "Check-in diário com relatório para o tutor",
    "Fotos e observações do dia",
    "Controle de vagas e grupos",
    "Financeiro com assinaturas recorrentes",
  ],
  faq: [
    { q: "Controlo planos mensais?", a: "Sim. Cada pet tem plano com frequência e você acompanha os check-ins do mês." },
    { q: "Mando relatório ao tutor?", a: "Sim. Você registra observações e fotos do dia (notificação automática a caminho)." },
  ],
  seo: {
    title: "Sistema para Creche para Pets | Planos e check-in",
    description: "Software para creche de pets com planos mensais, check-in, relatórios, fotos e financeiro.",
    keywords: ["sistema creche pet", "day care cães", "software creche animal"],
    headline: "O sistema da sua creche para pets",
    subheadline: "Planos mensais, check-in, relatórios, fotos e financeiro.",
  },
};

export const adestramento: SegmentTemplate = {
  id: "adestramento",
  label: "Adestramento",
  slug: "adestramento",
  icon: "Target",
  category: "pet",
  tagline: "Planos, evolução e relatórios.",
  modules: ["clients", "scheduling", "services", "records", "financial"],
  terms: {
    customer: "Tutor",
    customer_plural: "Tutores",
    professional: "Adestrador",
    professional_plural: "Adestradores",
    service: "Sessão",
    service_plural: "Sessões",
    appointment: "Aula",
    appointment_plural: "Agenda",
    records: "Evolução",
  },
  customerFields: [...petFields],
  defaultServices: [
    { name: "Avaliação comportamental", price: 150, durationMin: 60 },
    { name: "Pacote 8 sessões", price: 800, durationMin: 60 },
    { name: "Aula avulsa", price: 120, durationMin: 60 },
  ],
  benefits: [
    "Planos de adestramento com cronograma",
    "Evolução e relatórios por sessão",
    "Agenda por adestrador",
    "Pacotes de sessões com controle de uso",
    "Financeiro com planos e mensalidades",
  ],
  faq: [
    { q: "Registro a evolução do pet?", a: "Sim. Cada sessão tem evolução, observações e metas do plano de adestramento." },
    { q: "Vendo pacotes de sessões?", a: "Sim. Você cadastra pacotes e acompanha quantas sessões restam." },
  ],
  seo: {
    title: "Sistema para Adestramento | Planos e evolução",
    description: "Software para adestramento com planos, cronograma, evolução, relatórios e financeiro.",
    keywords: ["sistema adestramento", "software adestrador", "planos adestramento"],
    headline: "O sistema do seu adestramento",
    subheadline: "Planos, cronograma, evolução, relatórios e financeiro.",
  },
};

export const esteticaAnimal: SegmentTemplate = {
  id: "estetica-animal",
  label: "Estética Animal",
  slug: "estetica-animal",
  icon: "Sparkles",
  category: "pet",
  tagline: "Banho, tosa criativa e spa pet.",
  modules: ["clients", "scheduling", "services", "inventory", "financial", "team"],
  terms: {
    customer: "Tutor",
    customer_plural: "Tutores",
    professional: "Esteticista",
    professional_plural: "Esteticistas",
    service: "Serviço",
    service_plural: "Serviços",
    appointment: "Agendamento",
    appointment_plural: "Agenda",
    inventory: "Produtos / Estoque",
  },
  customerFields: [...petFields],
  defaultServices: [
    { name: "Spa completo", price: 120, durationMin: 90 },
    { name: "Tosa criativa", price: 150, durationMin: 120 },
    { name: "Hidratação de pelagem", price: 80, durationMin: 60 },
  ],
  benefits: [
    "Agenda de serviços estéticos por profissional",
    "Fotos antes e depois no histórico",
    "Produtos utilizados por atendimento",
    "Pacotes de spa e tosa criativa",
    "Preferências e restrições por pet",
  ],
  faq: [
    { q: "Guardo fotos dos serviços?", a: "Sim. Cada atendimento registra fotos antes e depois no histórico do pet." },
    { q: "Cadastro produtos usados?", a: "Sim. Você registra os produtos utilizados e baixa do estoque." },
  ],
  seo: {
    title: "Sistema para Estética Animal | Spa e tosa criativa",
    description: "Software para estética animal com spa, tosa criativa, fotos, produtos e financeiro.",
    keywords: ["sistema estética animal", "spa pet", "tosa criativa"],
    headline: "O sistema do seu centro de estética animal",
    subheadline: "Spa, tosa criativa, fotos, produtos e agenda.",
  },
};

export const petCenter: SegmentTemplate = {
  id: "pet-center",
  label: "Pet Center",
  slug: "pet-center",
  icon: "Store",
  category: "pet",
  tagline: "Shop, clínica, banho e hotel integrados.",
  modules: ["clients", "scheduling", "services", "records", "inventory", "financial", "team", "work_orders"],
  terms: {
    customer: "Tutor",
    customer_plural: "Tutores",
    professional: "Profissional",
    professional_plural: "Equipe",
    service: "Serviço",
    service_plural: "Serviços",
    appointment: "Agendamento",
    appointment_plural: "Agenda",
    records: "Prontuário",
    inventory: "Produtos / Estoque",
    work_order: "Internação / Reserva",
    work_order_plural: "Internações / Reservas",
  },
  customerFields: [...tutorFields, ...petFields],
  defaultServices: [
    { name: "Consulta veterinária", price: 150, durationMin: 30 },
    { name: "Banho e tosa", price: 90, durationMin: 90 },
    { name: "Diária hotel pet", price: 80, durationMin: 0 },
  ],
  benefits: [
    "Tudo integrado: shop, clínica, banho, hotel e creche",
    "Um cadastro de tutor e pet para todos os serviços",
    "Prontuário, agenda e PDV em um só sistema",
    "Estoque único de produtos, rações e medicamentos",
    "Financeiro consolidado por tutor",
  ],
  faq: [
    { q: "Unifico shop e clínica?", a: "Sim. O pet center opera shop, clínica, banho e hospedagem no mesmo sistema e cadastro." },
    { q: "Um pet, vários serviços?", a: "Sim. O histórico do pet reúne consultas, banhos, hospedagens e compras." },
  ],
  seo: {
    title: "Sistema para Pet Center | Shop, clínica e banho integrados",
    description: "Software para pet center com shop, clínica veterinária, banho e tosa, hotel, prontuário e estoque integrados.",
    keywords: ["sistema pet center", "erp pet center", "software pet integrado"],
    headline: "O ERP do seu pet center",
    subheadline: "Shop, clínica, banho, hotel e estoque em um só lugar.",
  },
};

export const petBoutique: SegmentTemplate = {
  id: "pet-boutique",
  label: "Pet Boutique",
  slug: "pet-boutique",
  icon: "Gift",
  category: "pet",
  tagline: "PDV premium, catálogo e fidelidade.",
  modules: ["clients", "services", "inventory", "financial", "team"],
  terms: {
    customer: "Tutor",
    customer_plural: "Tutores",
    professional: "Vendedor",
    professional_plural: "Vendedores",
    service: "Produto",
    service_plural: "Produtos",
    inventory: "Estoque",
  },
  customerFields: petFields,
  defaultServices: [
    { name: "Coleira premium", price: 89, durationMin: 0 },
    { name: "Camisa pet", price: 65, durationMin: 0 },
    { name: "Kit presente", price: 120, durationMin: 0 },
  ],
  benefits: [
    "PDV com catálogo e variações",
    "Programa de fidelidade e gift card — a caminho",
    "Cadastro de tutores e pets com preferências",
    "Estoque de acessórios premium",
    "Campanhas para aniversário do pet",
  ],
  faq: [
    { q: "Tenho catálogo online?", a: "O catálogo online integrado está no roadmap; hoje você opera o PDV e o estoque na loja." },
    { q: "Fidelidade para tutores?", a: "O programa de fidelidade e gift card está no roadmap; hoje você tem histórico de compras." },
  ],
  seo: {
    title: "Sistema para Pet Boutique | PDV e fidelidade",
    description: "Software para pet boutique com PDV, catálogo, fidelidade, gift card e estoque.",
    keywords: ["sistema pet boutique", "pdv pet premium", "loja acessórios pet"],
    headline: "O sistema da sua pet boutique",
    subheadline: "PDV premium, catálogo, fidelidade, gift card e estoque.",
  },
};

export const agropecuaria: SegmentTemplate = {
  id: "agropecuaria",
  label: "Agropecuária",
  slug: "agropecuaria",
  icon: "Leaf",
  category: "pet",
  tagline: "Produtos rurais, veterinário e estoque.",
  modules: ["clients", "scheduling", "services", "inventory", "financial", "team"],
  terms: {
    customer: "Cliente",
    customer_plural: "Clientes",
    professional: "Profissional",
    professional_plural: "Equipe",
    service: "Produto / Serviço",
    service_plural: "Produtos / Serviços",
    appointment: "Atendimento",
    appointment_plural: "Agenda",
    inventory: "Estoque",
  },
  customerFields: [
    { key: "propriedade", label: "Propriedade / fazenda", type: "text" as const },
    { key: "animais", label: "Tipo de animais", type: "text" as const },
  ],
  defaultServices: [
    { name: "Ração bovina (sc)", price: 0, durationMin: 0 },
    { name: "Medicamento veterinário", price: 0, durationMin: 0 },
    { name: "Consulta veterinária rural", price: 200, durationMin: 60 },
  ],
  benefits: [
    "PDV de produtos rurais e veterinários",
    "Agenda de atendimento veterinário rural",
    "Estoque de rações, medicamentos e insumos",
    "Controle de validade e lotes",
    "Financeiro com convênios e crediário",
  ],
  faq: [
    { q: "Vendo ração e medicamentos?", a: "Sim. O PDV e estoque cobrem rações, medicamentos e insumos agropecuários." },
    { q: "Agendo veterinário rural?", a: "Sim. Você agenda visitas e atendimentos na propriedade do cliente." },
  ],
  seo: {
    title: "Sistema para Agropecuária | Produtos e veterinário",
    description: "Software para agropecuária com PDV, produtos rurais, atendimento veterinário, estoque e financeiro.",
    keywords: ["sistema agropecuária", "software agropecuária", "pdv rural veterinário"],
    headline: "O sistema da sua agropecuária",
    subheadline: "PDV, produtos rurais, veterinário, estoque e financeiro.",
  },
};
